[buildPlans.iosevkata]
family = "Iosevkata"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

  [buildPlans.iosevkata.variants]
  inherits = "ss08"

    [buildPlans.iosevkata.variants.design]
    capital-j = "flat-hook-serifed"
    f = "flat-hook"
    g = "single-storey-flat-hook-serifless"
    j = "flat-hook-serifed"
    l = "serifed"
    m = "normal"
    r = "hookless"
    t = "flat-hook"
    u = "toothless-rounded"
    underscore = "high"
    caret = "medium"
    paren = "large-contour"
    number-sign = "upright"
    ampersand = "upper-open"
    at = "fourfold-solid-inner"
    dollar = "open-cap"
    percent = "dots"
    question = "corner-flat-hooked"
    punctuation-dot = "round"
    lig-double-arrow-bar = "without-notch"

[buildPlans.iosevkata.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevkata.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevkata.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"